import 'anime.dart';

const gamesList = [
  Game(
    title: 'The Witcher 3: Wild Hunt',
    description: 'Ведьмак Геральт ищет свою приёмную дочь в огромном открытом мире, полном чудовищ и магии.',
    genre: 'RPG, Открытый мир',
    year: 2015,
    rating: 9.5,
    developer: 'CD Projekt Red',
    imagePath: 'assets/images/game1.jpg',
  ),
  Game(
    title: 'Cyberpunk 2077',
    description: 'Погрузитесь в мрачное будущее Найт-Сити, где кибернетические импланты меняют правила игры.',
    genre: 'RPG, Экшен',
    year: 2020,
    rating: 8.5,
    developer: 'CD Projekt Red',
    imagePath: 'assets/images/game2.jpg',
  ),
  Game(
    title: 'Red Dead Redemption 2',
    description: 'Эпическая история бандита Артура Моргана в эпоху заката Дикого Запада.',
    genre: 'Экшен, Приключения',
    year: 2018,
    rating: 9.8,
    developer: 'Rockstar Games',
    imagePath: 'assets/images/game3.jpg',
  ),
  Game(
    title: 'God of War Ragnarök',
    description: 'Кратос и Атрей отправляются в путешествие по девяти мирам, чтобы предотвратить Рагнарёк.',
    genre: 'Экшен, Приключения',
    year: 2022,
    rating: 9.6,
    developer: 'Santa Monica Studio',
    imagePath: 'assets/images/game4.jpg',
  ),
  Game(
    title: 'Elden Ring',
    description: 'Исследуйте огромный мир, сражайтесь с могущественными боссами и раскройте тайны Кольца.',
    genre: 'RPG, Souls-like',
    year: 2022,
    rating: 9.7,
    developer: 'FromSoftware',
    imagePath: 'assets/images/game5.jpg',
  ),
    Game(
    title: 'The Legend of Zelda: Tears of the Kingdom',
    description: 'Линк исследует небесные острова и подземелья Хайрула, используя новые способности.',
    genre: 'Приключения, Открытый мир',
    year: 2023,
    rating: 9.7,
    developer: 'Nintendo',
    imagePath: 'assets/images/game6.jpg',
  ),
  Game(
    title: 'Baldur\'s Gate 3',
    description: 'Эпическая CRPG по мотивам D&D, где ваш выбор формирует историю.',
    genre: 'RPG, Пошаговая',
    year: 2023,
    rating: 9.8,
    developer: 'Larian Studios',
    imagePath: 'assets/images/game7.jpg',
  ),
  Game(
    title: 'Hollow Knight',
    description: 'Путешествуйте по подземному королевству жуков, сражайтесь с врагами и раскрывайте тайны.',
    genre: 'Метроидвания, Платформер',
    year: 2017,
    rating: 9.4,
    developer: 'Team Cherry',
    imagePath: 'assets/images/game8.jpg',
  ),
  Game(
    title: 'Disco Elysium',
    description: 'Детективная RPG с уникальной системой навыков, где вместо боёв — диалоги.',
    genre: 'RPG, Детектив',
    year: 2019,
    rating: 9.6,
    developer: 'ZA/UM',
    imagePath: 'assets/images/game9.jpg',
  ),
  Game(
    title: 'Stardew Valley',
    description: 'Унаследуйте старую ферму, выращивайте урожай, общайтесь с жителями и исследуйте пещеры.',
    genre: 'Симулятор, Ферма',
    year: 2016,
    rating: 9.2,
    developer: 'ConcernedApe',
    imagePath: 'assets/images/game10.jpg',
  ),
];